repos:
  - repo: local
    hooks:
      - id: tsc-typescheck
        name: tsc-typescheck
        language: system
        description: Run `tsc` compiler to check project files
        entry: npx tsc --noEmit
        types: ["ts"]
      - id: elm-check
        name: elm-check
        language: system
        description: Run `elm` compiler to check project files
        entry: npx elm make --output=/dev/null
        types: ["file"]
        files: \.elm$
